# Generated by Django 6.0.4 on 2026-04-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Placed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('PICKED_UP', 'Picked Up')], default='PLACED', max_length=50),
        ),
    ]
