# Generated by Django 6.0.4 on 2026-05-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
