# Generated by Django 6.0.4 on 2026-05-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
    ]
